version: '3.7'
services:
  osparc-python-inter-runner:
    image: simcore/services/dynamic/osparc-python-inter-runner:0.0.8
    ports:
      - "8888:8888"
    environment:
      - DY_SIDECAR_PATH_INPUTS=/tmp/inputs
      - DY_SIDECAR_PATH_OUTPUTS=/tmp/outputs
      - DY_BOOT_OPTION_BOOT_MODE=0
      - DY_SIDECAR_PATH=/home/jovyan/work/workspace
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${PWD}/validation/workspace:/home/jovyan/work/workspace
      - ${PWD}/validation/inputs:/tmp/inputs
      - ${PWD}/validation/outputs:/tmp/outputs
